### ISSUE TITLE
为什么会结尾不是 } ？

### ISSUE THREAD

**Issue by zunsthy** [xcatliu/chatgpt-next#1]
https://github.com/xcatliu/chatgpt-next/blob/d2c62ee79b5403466a2bb329c9ca0444bdc20cd7/pages/api/chat.ts#L64

这里是指内容没接收全吗？

**Comment by xcatliu** [comment]
@zunsthy 结尾是花括号时，表示e.message可能是序列化的json字符串，但是又不完全是，因为前面会有一段额外字符。比如e.message可能是这样的：ChatGPTError: Invalid key {"code":"938","message":"some detail"}
