### ISSUE TITLE
代码输出编辑器没有

### ISSUE THREAD

**Issue by zhaohai1024** [xcatliu/chatgpt-next#21]

**Comment by xcatliu** [comment]
这是什么意思？是指这个 #18 吗？

**Comment by zhaohai1024** [comment]
> 

<img width="1108" alt="iShot_2023-03-19_11 27 19" src="https://user-images.githubusercontent.com/127855845/226151980-dc913741-0d4b-401f-9704-a8d7f25081d2.png">

**Comment by xcatliu** [comment]
哦，就是代码高亮和 copy code 功能吧，这个在计划中了

**Comment by xcatliu** [comment]
把你的提问发给我试试吧？

**Comment by zhaohai1024** [comment]
写一个php简单的例子
