### ISSUE TITLE
如果输入html标签的话，需转义回显. 

### ISSUE THREAD

**Issue by popable** [xcatliu/chatgpt-next#34]
您好，体验了一下非常棒。
有个小问题，输入html标签的时候未能正确回显，
输入
```<h1>abc</h1>```
直接显示为html了 <h1>abc</h1> ,而不是html代码```<h1>abc</h1>```。

**Comment by xcatliu** [comment]
确实是 bug，感谢反馈！

**Comment by xcatliu** [comment]
已修复，顺序修复了多个空格被合并成一个的 bug

**Comment by popable** [comment]
赞！
