### ISSUE TITLE
能否支持显示一下图片

### ISSUE THREAD

**Issue by guinanlin** [xcatliu/chatgpt-next#52]
关键词： 那你画个抛物线的图吧 y = 10x^2 + 2x + 3

会有图像的回传， 这个能不能展示一下的？

**Comment by xcatliu** [comment]
能看下你的回传是什么样的吗？我的好像不太对

**Comment by guinanlin** [comment]
| 
  120 |-                                                  
      |    __                                           
      |   /  \                                         
      |  /    \                                        
   80 |-/      \                                       
      |         \                                   
      |          \                                  
   40 |            \                                 
      |             \                                
      |              \                               
    0 |_______________\_______________________________
                      -2     0     2     4     6     8     

我这边显示结果是markdown

**Comment by guinanlin** [comment]
可以看这个图 [图片](https://pic.imgdb.cn/item/6422bda6a682492fccaa9a59.jpg)

**Comment by xcatliu** [comment]
已支持显示代码
