### ISSUE TITLE
为什么用Zeabur一键部署后，用域名访问不了呢，原项目代码还需要更改呢里吗

### ISSUE THREAD

**Issue by smofox** [xcatliu/chatgpt-next#60]
为什么用Zeabur一键部署后，用域名访问不了呢，原项目代码还需要更改呢里吗

**Comment by xcatliu** [comment]
@MichaelYuhe 帮忙看下这里的问题吧，谢谢

**Comment by MichaelYuhe** [comment]
可以点击重新部署，如果还是不行的话需要删除服务，重新导入试试看～

**Comment by xcatliu** [comment]
最近改过接口有影响吗？改成了stream模式

**Comment by MichaelYuhe** [comment]
> 最近改过接口有影响吗？改成了stream模式

不是这个的原因，是我们最近对于 Docker 的部署做了一点调整，有情况漏考虑了，现在补上了～
