### ISSUE TITLE
访问 OpenAI 失败

### ISSUE THREAD

**Issue by INBreezefall** [xcatliu/chatgpt-next#61]
Windows 11 Docker 4.18，本机代理是开着的但无法访问，容器内 ping 外面的 IP 可通。

是否可以将 body 打印出来？好歹知道是什么内容。看不太懂 Node.js 不知道如何查看更详细日志，有 Debug 模式吗？Readme 没提到

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/33120916/232738912-e064b25d-d771-4a75-ac50-b766f7bc54f4.png">

**Comment by xcatliu** [comment]
fetch failed 应该就是被墙了所以没通。

容器内确定能调的通 api.openai.com 的接口吗？

**Comment by INBreezefall** [comment]
我找到错误了——容器内缺乏 DNS 解析，需要在 解析文件中增加 Google 公共 DNS
具体解决方案如下

vi /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
