### ISSUE TITLE
似乎读历史有些问题，清理后正常

### ISSUE THREAD

**Issue by popable** [xcatliu/chatgpt-next#65]
![image](https://github.com/xcatliu/chatgpt-next/assets/117506276/3b88a9e8-74f9-4a87-968f-296e23fe14db)
![image](https://github.com/xcatliu/chatgpt-next/assets/117506276/e1d5350a-97c9-4a3d-935b-b1c9b240017d)

**Comment by xcatliu** [comment]
是刚升级过新版本出现的吗？

**Comment by popable** [comment]
上一个版本出现的，更新最新版本后也会出现。docker安装。

**Comment by xcatliu** [comment]
旧版和新版之间有个数据格式的升级，我已经尽可能做好兼容了，但可能无法保证100%没问题。不过清除数据后应该就会没问题了。如果后续又出现这个bug再麻烦反馈一下哈
