### ISSUE TITLE
会出现 网络问题后，无法继续使用

### ISSUE THREAD

**Issue by nightamber** [xcatliu/chatgpt-next#68]
<img width="469" alt="image" src="https://github.com/xcatliu/chatgpt-next/assets/26924871/76e0619a-619c-45af-b25a-bcf83c0944e1">

**Comment by xcatliu** [comment]
感谢反馈，可以复现

**Comment by xcatliu** [comment]
@nightamber 已修复

**Comment by liangwei-artefact** [comment]
谢谢 大佬！
