### ISSUE TITLE
支持https链接协议

### ISSUE THREAD

**Issue by sacrrie** [xcatliu/chatgpt-next#69]
请问下一步开发有计划支持https协议吗？http链接到自己服务器裸奔的感觉不太好。

**Comment by sacrrie** [comment]
我再找找部署资料，开发者给出的例子都是https

**Comment by xcatliu** [comment]
感谢支持😆

支持 https 哦，可以参考我这个配置。
我这个是通过 https://letsencrypt.org/zh-cn/getting-started/ 自动配置好 https 的。可以参考[这个文档](https://letsencrypt.org/zh-cn/getting-started/) 安装 Certbot 然后执行一个脚本就搞定了
