### ISSUE TITLE
聊着聊着左边的会话就乱了

### ISSUE THREAD

**Issue by lijicheng123** [xcatliu/chatgpt-next#71]
当你左边有几个会话的时候，如果选中其中一个聊天，再点击任意一个会话都无法选中，回选中到别的会话，除非再次点击选择

**Comment by xcatliu** [comment]
有能稳定复现的流程吗？

**Comment by lijicheng123** [comment]
1、刷新页面
2、点击第三个会话并进行聊天
3、切换到其他会话，此时会发现切换不对，会切到另外一个会话中

**Comment by xcatliu** [comment]
已修复
